from setuptools import setup, find_packages

setup(
    name="AIRouter",
    version="1.0.0",
    description="AIRouter: 智能AI路由器，提供统一的LLM调用接口，支持多源负载均衡和故障转移",
    long_description="AIRouter是一个高性能的AI路由和负载均衡工具，为多个LLM提供商提供统一的API接口，支持智能路由、故障转移和性能监控。",
    packages=find_packages(),
    py_modules=['LLMwrapper', 'LoadBalancing', 'CheckHealthy'],
    install_requires=[
        "fastapi>=0.95.0",
        "uvicorn>=0.21.1",
        "apscheduler>=3.10.1",
        "numpy>=1.24.2",
        "matplotlib>=3.7.1",
        "seaborn>=0.12.2",
        "tqdm>=4.65.0",
        "python-multipart>=0.0.6",
        "requests>=2.28.0",
        "openai>=1.0.0",
        "sqlalchemy>=2.0.0",
        "pymysql>=1.0.0",
        "cryptography>=39.0.0",
    ],
    python_requires=">=3.7",
    author="AIRouter Team",
    author_email="contact@airouter.dev",
    url="https://github.com/your-username/AIRouter",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8", 
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Operating System :: OS Independent",
    ],
    keywords="ai llm router load-balancing api-gateway openai anthropic",
    project_urls={
        "Bug Reports": "https://github.com/your-username/AIRouter/issues",
        "Source": "https://github.com/your-username/AIRouter",
        "Documentation": "https://github.com/your-username/AIRouter#readme",
    },
) 